_target_: src.data.gpsl_distributed_datamodule.DistributedDataModule
num_clients: 32
subset_config:
  distribution: "iid"
  params:
    C: 2
    alpha: 3

sampler:
  _target_: "src.utils.sampling.UniformGlobalSampler"
  _partial_: true