# @package _global_
defaults:
  - override /hydra/sweeper: basic
  - override /hydra/launcher: joblib

hydra:
  mode: MULTIRUN
  launcher:
    n_jobs: 1
  sweeper:
    params:
      seed: 1,2,3,4,5
      data.batch_size: 64,128,256