_target_: src.models.gpsl_module.GPSLModule

model:
  _target_: "models.components.torchvision_wrappers.resnet18"
  _partial_: true

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.01
  # weight_decay: 0.0005
  # momentum: 0.9

loss_fn:
  _target_: "torch.nn.functional.cross_entropy"
  _partial_: true

cut_layer: "layer2"

gn_num_groups: 32

num_clients: ${distributed.num_clients}

# compile model for faster training with pytorch 2.0
# compile: false
